repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --profile black
        language: system
        types: [python]
      - id: black
        name: black
        entry: black . --include src/ --include tests/
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8 src/
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy src/
        pass_filenames: false
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: bandit -c pyproject.toml -r src
        language: system
        types: [python]
